config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root "home#index"

  resources :cars
  resources :supplies
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get '/query/' => 'supplies#query', as: 'query'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CronappKm" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag '/photo6.ico' %>

    <!-- For third-generation iPad with high-resolution Retina display: -->


    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->


    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body style="background-color: #DCDCDC;">


    <div class="navbar navbar-default navbar-static-top" style="background-color: #00CED1;">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><font color="white"><%=image_tag '/photo6.ico'%> CronappKm</font></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <font color="white"> Logged in as</font></a><strong><font color="white"> <%= current_user.email %></font></a></strong>.
              <li><%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link', :style=>'color: white;'  %></li>
                <li><%= link_to "Meus Carros", cars_path, method: :get, :class => 'navbar-link', :style=>'color: white;'  %></li>
                  <li><%= link_to "Meus Abastecimentos", supplies_path, method: :get, :class => 'navbar-link', :style=>'color: white;'  %></li>
                  <li><%= link_to "Sair", destroy_user_session_path, method: :get, :class => 'navbar-link', :style=>'color: white;'  %></li>
            <% else %>
                <li> <%= link_to "Cadastre-se", new_user_registration_path, :class => 'navbar-link',:style=>'color: white;' %> </li>
                <li>  <%= link_to "Entrar", new_user_session_path, :class => 'navbar-link', :style=>'color: white;'  %>   </li>
                <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      <footer>

      </footer>

    </div> <!-- /container -->

  </body>
</html>